# Generated by Django 3.1.5 on 2021-03-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0002_remove_details_u_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_gender', models.CharField(choices=[('Male', 1), ('Female', 2)], default='Male', max_length=6)),
            ],
        ),
    ]
