# Generated by Django 3.1.5 on 2021-03-23 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='u_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='u_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='data',
            name='u_title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='u_name',
            field=models.TextField(max_length=10000),
        ),
    ]
