# Generated by Django 3.1.5 on 2021-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0005_auto_20210323_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='u_name',
            field=models.TextField(max_length=10000),
        ),
    ]
