# Generated by Django 3.1.5 on 2021-03-29 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogging', '0006_auto_20210324_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='u_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='login',
            name='u_pwd',
            field=models.CharField(max_length=20),
        ),
    ]
