# Generated by Django 3.1.5 on 2021-03-29 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0007_auto_20210329_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='u_name',
            new_name='u_content',
        ),
    ]
